# Generated by Django 5.0.1 on 2024-04-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telegram_id', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('telegram_fullname', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('kaspi_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.JSONField(blank=True, null=True)),
                ('exact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bonus', models.IntegerField(default=1000)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('client', 'Client'), ('admin', 'Admin'), ('delivery', 'Delivery')], default='Client', max_length=10)),
                ('blocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activeActions', models.ManyToManyField(blank=True, related_name='active_users', to='loyalty.action')),
                ('promo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.promos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
