# Generated by Django 5.0.1 on 2024-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('telegram_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, default=0, null=True)),
                ('history', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(blank=True, default='user', max_length=255, null=True)),
                ('blocked', models.JSONField(blank=True, default=dict, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
