version: '3'

services:
  app:
    build: .
    image: django_copy
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-cont
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rasul2004
