# Generated by Django 5.0.1 on 2024-03-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('can_be_triggered', models.BooleanField(default=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('payloads', models.ManyToManyField(to='loyalty.payload')),
                ('triggers', models.ManyToManyField(to='loyalty.trigger')),
            ],
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link_to_source', models.CharField(max_length=255, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyalty.action')),
            ],
        ),
    ]
