# Generated by Django 5.0.1 on 2024-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanySpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('address', models.JSONField()),
                ('address_link', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additions_on_stop', models.ManyToManyField(to='food.addition')),
                ('products_on_stop', models.ManyToManyField(to='food.product')),
                ('delivery_layers', models.ManyToManyField(to='service.deliverylayers')),
            ],
        ),
    ]
