# Generated by Django 5.0.1 on 2024-03-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyspots',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_companies', to='my_auth.customuser', unique=True),
        ),
    ]
