# Generated by Django 5.0.1 on 2024-01-25 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('client_comment', models.TextField()),
                ('active_modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.modifier')),
                ('additions', models.ManyToManyField(blank=True, to='food.addition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('status', models.CharField(choices=[('payment_await', 'Payment Await'), ('manager_await', 'Manager Await'), ('active', 'Active'), ('done', 'Done'), ('on_delivery', 'On Delivery'), ('inactive', 'Inactive')], default='payment_await', max_length=20)),
                ('bonus_used', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255)),
                ('loc', models.FloatField()),
                ('lat', models.FloatField()),
                ('exact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='food.orderproduct')),
            ],
        ),
    ]
