# Generated by Django 5.0.1 on 2024-03-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('my_auth', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.companyspots'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_auth.customuser'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='active_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.modifier'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='additions',
            field=models.ManyToManyField(blank=True, to='food.addition'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='food.orderproduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='additions',
            field=models.ManyToManyField(blank=True, null=True, to='food.addition'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifiers',
            field=models.ManyToManyField(blank=True, null=True, to='food.modifier'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='food.tag'),
        ),
    ]
