# Generated by Django 5.0.1 on 2024-03-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='my_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='my_auth.customuser'),
            preserve_default=False,
        ),
    ]
