# Generated by Django 5.0.1 on 2024-01-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_orderproduct_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='product_id',
        ),
    ]
