# Generated by Django 5.0.1 on 2024-03-14 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_order_lat_remove_order_long_order_address'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='my_auth.customuser'),
        ),
    ]
