# Generated by Django 5.0.1 on 2024-01-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
