# Generated by Django 5.0.1 on 2024-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_addition_price_alter_modifier_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='client_comment',
            field=models.TextField(blank=True),
        ),
    ]
