# Generated by Django 5.0.1 on 2024-03-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_order_delivery_id'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='my_auth.customuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='food.orderproduct'),
        ),
    ]
