# Generated by Django 5.0.1 on 2024-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kaspi_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
