# Generated by Django 5.0.1 on 2024-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
